---
name: Martin
surname: Čadek
position: "Data Scientist | PhD"
address: ""
# www: www.martincadek.com
email: "cadekmail@gmail.com"
github: ""
linkedin: martincadek
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: 414141
aboutme: "I am employed as a Data Scientist at Roche, where I lead the end-to-end delivery of reproducible analyses and statistics for clinical trials focused on studying obesity using R, Python, and SAS. I have over five years of experience in data science, and I am passionate about reproducible research, open-source projects, and socially impactful work. I hold a PhD in Public Health and Obesity, a Master’s Degree in Psychology, and a Postgraduate Certificate in Data Science and Statistics."
output: 
     vitae::awesomecv:
          page_total: true
---


```{r setup_vitae, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
options(tinytex.verbose = TRUE)
library(vitae) 
# https://pkg.mitchelloharawild.com/vitae/
# https://github.com/tallguyjenks/CV (inspired by)
# http://chrisumphlett.com/posts/vitae-package/ (inspired by)
# Additional R Packages:
library(tibble)
library(dplyr)
library(tinytex)
library(glue)
library(here)

```


```{r setup_others, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
source(file = here("data/experience.R")) # R file with experiences section
source(file = here("data/courses.R")) # R file with courses section
source(file = here("data/community.R")) # R file with community section
source(file = here("data/education.R")) # R file with education section
source(file = here("data/skills.R")) # R file with skills section
```

# Skills

```{r skills}
skills %>% 
  detailed_entries(category, activity, location, dates, details)
```


# Experience

```{r experience}
# The .protect = FALSE allows latex to be implemented;
# Not used in other parts
experience %>% 
     detailed_entries(role, dates, company, location, details, .protect = FALSE)
```

<!-- # Courses -->

```{r courses, echo=FALSE, results='hide', message=FALSE}
courses %>% 
  detailed_entries(organisation, dates, category, location, description)
```

<!-- # Community -->

```{r community, echo=FALSE, results='hide', message=FALSE}
community %>%
  detailed_entries(role, dates, activity, location, details)
```

# Education

```{r education}
education %>% 
  detailed_entries(degree, dates, uni, loc) # , details
```
